j1:
  i2c_address: '0x11'
  reduction: 35
  min: -3.04647
  max: 3.04647
  stall_threshold: 6
  hold_current: 20
  drive_current: 20
  max_acceleration: 2.0
  max_velocity: 1.0
  homing:
    speed: 0.03
    threshold: 30
    current: 15
    acceleration: 0.01
j2:
  i2c_address: '0x12'
  reduction: -1570.79632679 # -2*pi/0.004
  min: -0.0016
  max: 0.338
  stall_threshold: 12 # Stall detection unlikely on J2 anyway
  hold_current: 40
  drive_current: 40
  max_acceleration: 0.2
  max_velocity: 0.03
  homing:
    speed: 0.003
    threshold: 50
    current: 30
    acceleration: 0.001
j3:
  i2c_address: '0x13'
  reduction: 24
  min: -2.62672
  max: 2.62672
  stall_threshold: 6
  hold_current: 20
  drive_current: 20
  max_acceleration: 14.0
  max_velocity: 5.0
  homing:
    speed: 0.05
    threshold: 25
    current: 10
    acceleration: 0.01
j4:
  i2c_address: '0x14'
  reduction: 12
  min: -3.01069
  max: 3.01069
  stall_threshold: 6
  hold_current: 20
  drive_current: 20
  max_acceleration: 30.0
  max_velocity: 10.0
  homing:
    speed: 0.1
    threshold: 30
    current: 10
    acceleration: 0.1
