controller_manager:
  ros__parameters:
    # joint_state_broadcaster is treated as a 'controller', needs to be provided.
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    update_rate: 50
      
