# Limits for the Pilz planner
# They should be chosen so conservative that joint limits are not exceeded. LIN paths will adhere to these limits but will fail
# if joint limits are exceeded. By reducing these limits one can reduce the chance that happens.
cartesian_limits:
  max_trans_vel: 0.1
  max_trans_acc: 0.25
  max_trans_dec: -.25
  max_rot_vel: 1.57
