controller_manager:
  ros__parameters:
    # joint_state_broadcaster is treated as a 'controller', needs to be provided.
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    # I need to specify the type here otherwise the following error message is thrown on controller activation:
    #  "The 'type' param was not defined for 'velocity_joint_trajectory_controller'"
    velocity_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    position_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    homing_controller:
      type: single_trigger_controller/SingleTriggerController
    

    update_rate: 50

    # hardware_components_initial_state:
    #   inactive:
    #     - "bioscara"
    
    defaults:
      allow_controller_activation_with_inactive_hardware: false

position_joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - j1
      - j2
      - j3
      - j4

    command_interfaces:
      - position

    state_interfaces:
      - position
      
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    interpolate_from_desired_state: false
  
velocity_joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - j1
      - j2
      - j3
      - j4

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity
      
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    interpolate_from_desired_state: false

    gains:
      j1:
        p: 0.5
        # i: 1.0
        # d: 0.0
        ff_velocity_scale: 1.0
        antiwindup_strategy: none
      j2:
        p: 0.5
        # i: 1.0
        # d: 0.0
        ff_velocity_scale: 1.0
        antiwindup_strategy: none
      j3:
        p: 0.5
        # i: 1.0
        # d: 0.0
        ff_velocity_scale: 1.0
        antiwindup_strategy: none
      j4:
        p: 0.5
        # i: 1.0
        # d: 0.0
        ff_velocity_scale: 1.0
        antiwindup_strategy: none
      
homing_controller:
  ros__parameters:
    type: single_trigger_controller/SingleTriggerController
    gpios:
      - j1
      - j2
      - j3
      - j4
    command_interfaces:
      j1:
        - interfaces:
          - home
      j2:
        - interfaces:
          - home
      j3:
        - interfaces:
          - home
      j4:
        - interfaces:
          - home